### ISSUE TITLE
Not found in the config folder of my aternos server [BUG]

### ISSUE THREAD

**Issue by WhiteArtz** [MianReplicate/Lifesteal#1]
**Versions**
Minecraft Version: 1.19.2
Forge Version: Don't know sorry
Mod Version: [1.19.2 Release 3.2.2]

**Describe the bug**
First, sorry, it's not really an bug i think or is it? Because as said in the description, the .toml file was supposed to be in the config folder, but somehow i couldn't find it. I am using an aternos server and checked the config folder, but couldn't find it anywhere.

**To Reproduce**
1. Go to Aternos, create your own server and then click on 'Mods' 
2. Click on 'Config'
3. Search lifesteal-common.toml
4. See no toml. :(

**Expected behavior**
The ''lifesteal-common.toml'' wasn't anywhere to be found.

**Screenshots**
![image](https://user-images.githubusercontent.com/127995833/225444807-10c3e05a-644c-42f2-91d2-e4c7d969acfa.png)

**Additional context**
Like i said before, sorry but i really don't know where i can find the .toml file to configure the mod :( and i really like to know why. And thank you!

**Comment by MianReplicate** [comment]
Hi there! I see you're having a problem with the config, but here are some things you need to know first.

First off, you're writing this issue on the wrong page. It should be in the "Lifesteal" repository and not "Lifesteal-Forge". Though that's okay I can just move the issue over.

Second, did you run the server once after you add the mod? If not, do so and then come back to me and tell me if the config file is there.

**Comment by WhiteArtz** [comment]
Alright, will do after school! :)

**Comment by WhiteArtz** [comment]
Hello again! It wasn't there for some reason, but after i reinstalled it, and went into the game, it lastly appeared :)

Thank you for helping me!

[Also sry for the late reply, i was busy studying]

**Comment by MianReplicate** [comment]
No problem :)
