### ISSUE TITLE
Better compatibility with Origins

### ISSUE THREAD

**Issue by crispeeweevile** [MianReplicate/Lifesteal#11]
**Is your feature request related to a problem? Please describe.**
In the Origins mod, certain Origins cannot use Heart Crystals. Particularly the arachnid cannot, since it can only eat meat, and the Heart Crystals are not meat.

**Describe the feature you'd like**
Perhaps instead of heart crystals being food, they could just be some other type of item? Or just a way to make it so the Heart Crystals are both meat and not meat

**Describe alternatives you've considered**
Maybe a meat and non meat version which are interchangeable?

**Comment by MianReplicate** [comment]
Could you try making Heart Crystals instant-use in the config first to see if that works? I believe that MIGHT work but I'm not sure.

**Comment by MianReplicate** [comment]
If not, I could make a config instead to make Heart Crystals give food points to the player to count as meat.

**Comment by crispeeweevile** [comment]
> Could you try making Heart Crystals instant-use in the config first to see if that works? I believe that MIGHT work but I'm not sure.

Didn't seem to fix it

> If not, I could make a config instead to make Heart Crystals give food points to the player to count as meat.

I don't think that they would need to give food points, I think it's some sort of tag, but I'm not sure how to check

**Comment by MianReplicate** [comment]
Hi! I apologize for not responding for quite some time. I haven't been working on the mod much and so I couldn't get to your suggestion while also trying to make sure I got the mod ported to newer versions of MC.

Checking on the tags, it is a tag I need to give to the items for them to be considered "meat" for Origins. Thank you for letting me know and I will get this fixed in the newer versions of the mod asap!

**Comment by MianReplicate** [comment]
This should be fixed now but I can't really check because Origins is only for 1.20.2 and below haha. The tag is added though for the upcoming update and should work with any future updates for Origin!👍
