### ISSUE TITLE
Player gains all health back upon re-joining the server.

### ISSUE THREAD

**Issue by Blocks789** [MianReplicate/Lifesteal#16]
**Versions**
Minecraft Version: 1.21
Fabric Loader Version: 0.15.11
Fabric API Version: 0.100.4
Mod Version: Release 9.1.1

Whenever I happen to leave and re-join my minecraft server, all my health is gained back.

**Steps to reproduce the behavior:**
1. Take damage in a lifesteal server with no saturation.
2. Leave and re-join the server
3. Your health (not hearts) is immediately gained back.

**Expected Behaviour:**
My health stays as it was before leaving.

**Additional context**
These are my only mods on the server:
![image](https://github.com/MianReplicate/Lifesteal/assets/86410036/73b61986-c483-4b00-a10c-86e1d92011b8)

**Comment by Blocks789** [comment]
I've tested this in a singleplayer world with the same effect, (antixray, modernfix, and vcinteraction are all server-side, which i don't have in my mods folder for singleplayer)

**Comment by MianReplicate** [comment]
I'll take a look soon, thank you for the report!
