### ISSUE TITLE
Can't figure out how to revive

### ISSUE THREAD

**Issue by this-is-taken** [MianReplicate/Lifesteal#2]
I know this probably doesn't need to be on GitHub, but I couldn't find anywhere else to ask. Help.

**Comment by MianReplicate** [comment]
There's a discord for this? I've listed it in all my mods for support.

**Comment by this-is-taken** [comment]
Where is the discord? I've looked in CurseForge and Modrinth but I can't find anything about Discord.

**Comment by MianReplicate** [comment]
https://discord.gg/2h3pkECbdn

**Comment by this-is-taken** [comment]
Thanks
