### ISSUE TITLE
Heart limit set

### ISSUE THREAD

**Issue by Ozn0k** [MianReplicate/Lifesteal#25]
Hello, is there any way to set a heart limit so that in an smp people won't have a lot of hearts?

**Comment by MianReplicate** [comment]
Hi, yes there is. You can find a setting to turn this on within the Lifesteal configuration file in your server's config folder. It'll be under a category called "Maximums."

By the way, if possible, please use our discord for questions :). You'll get much faster responses as the issue tracker here is meant for issues specifically.
