### ISSUE TITLE
Game bans me when I loose 5 hearts 

### ISSUE THREAD

**Issue by Jakubik-232** [MianReplicate/Lifesteal#26]
When I die 5 times game bans me and it says that I lost all of my maximum hearts . I want it to ban me after I loose all my hearts . I tried changing it in the config file but it didnt work . 
There's only one value that it related to this : "Maximum number of Hitpoints you can Lose:" = 1 . Is it a bug or is it my fault ? Let me know

**Comment by MianReplicate** [comment]
This is a bug that I'm aware of already. It will be fixed when I have time :)

**Comment by Jakubik-232** [comment]
> This is a bug that I'm aware of already. It will be fixed when I have time :)

It's good to know , I hope you'll do that soon
