### ISSUE TITLE
Config could use some improvements

### ISSUE THREAD

**Issue by crispeeweevile** [MianReplicate/Lifesteal#4]
**Is your feature request related to a problem? Please describe.**
The config can be a little hard to understand at times, particularly since the explanations aren't always perfectly clear.

**Describe the feature you'd like**
Just some improvements to the explanations which make them more clear and concise

**Describe alternatives you've considered**
Reading the config very carefully (a couple of times)

**Additional context**
Posted an issue because I thought there was a bug, turns out I just didn't understand the config

Edit: also planning to actually work on this right now.

**Comment by MianReplicate** [comment]
If you wanna make a PR for this, go ahead! I'm not great at explanations haha so it'd be good if someone did them for me.

**Comment by crispeeweevile** [comment]
> If you wanna make a PR for this, go ahead! I'm not great at explanations haha so it'd be good if someone did them for me.

I'm just about done doing all the explanations, and then I'll make a PR. I'm not very good at this though (open source stuff, and I'm pretty new to Github) so you should look over it a bit to make sure I didn't mess something up.

**Comment by MianReplicate** [comment]
I'll take a look tomorrow, I gotta sleep for now as it's 1 AM.

**Comment by MianReplicate** [comment]
It looks mostly good!! I think a few configs were misunderstood by my original explanations unfortunately though so some of the new explanations are a bit off.

The (maximum hit points losable) config makes it impossible to be eliminated as you only get eliminated at 0 hearts, so it quite literally prevents you from being eliminated. Though I might make a config in the future later where you can be eliminated when you reach that limit.

**Comment by crispeeweevile** [comment]
> It looks mostly good!! I think a few configs were misunderstood by my original explanations unfortunately though so some of the new explanations are a bit off.
> 
> The (maximum hit points losable) config makes it impossible to be eliminated as you only get eliminated at 0 hearts, so it quite literally prevents you from being eliminated. Though I might make a config in the future later where you can be eliminated when you reach that limit.

Ahh I see, yeah I suppose it was misunderstood a bit then
